# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('national_identifier', models.BigIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(choices=[(1, 'Employee'), (2, 'Manager'), (3, 'CEO')])),
                ('job', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('marital_status', models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Married')])),
                ('salary', models.PositiveIntegerField()),
                ('activated', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('wife', 'Wife'), ('child', 'Child'), ('husband', 'Husband')], max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employees')),
            ],
        ),
    ]
