# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('national_identifier', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('Positions', models.PositiveIntegerField(choices=[(1, 'Employee'), (2, 'Manager'), (3, 'CEO')])),
                ('job', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('marital_status', models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Married')])),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
