# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180225_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='national_identifier',
            field=models.BigIntegerField(),
        ),
    ]
