# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180225_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='deduction',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='earning',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
