# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180225_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='deduction',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='earning',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
