# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180225_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
