# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='deduction_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='earning_description',
            field=models.TextField(null=True),
        ),
    ]
